git:
  depth: 3
env:
  global:
  - secure: "mD3RBWzc5aThrUKa60flWefcyZf2RWqtz15x7/keuIuVZVLs6pxxJr2W5jAY945iJRxSpvkiWYaa4ADjcNUitJ2xSaF9K9onn83QD7i03+4fyptqa7ZU3CJx+J+BmiKQT4vbFhzMEjxwHWQsQ5ufXeEW+O1irJl/IEUUpJPsn7eaiwR6Ke5HfhCQ13M/efHceewKfvUMcMPkL3xPAyzgor5QEns7UNUdSGUPplrNGYOoy8p1F6WSwhF1c0OymhN7RMGRvG2krgOeyFaw7lQeIjJZoU1xRb0GSydAF/EiL18bCSyxOfQtVHoPVurQ6OZYamV6qP7SbdIJyFewvcp2wUH7h8DgGbie2/fOw2CpjhSJqyqWWHZdvZJt0gM4MA/CtdDre5M6SUIq0FrNC+qIF6ROfcwvlUpcOfV78bo4UWo6aBV0CvJ5KmZl6fCiAUhjuOMVCnx6SHrrjiyD1YPa7pDLRenHM66rrttgI+39WvuF1cInCD/XOinNy7gbxE+gA2OtVhKQCixaTFchLPuG8lrLTIhyteHk+D/FaP0TeF2sTJ4coze1M1XuXCyDlHEc+lgMsR0zNNtgAQeQANVeKh9ITkJWfxELLv7S/W9axySWseWxC0S4Y2PN0JALcAZjNwq73uLWCgiOPHIs+ygVlYEUHyTOPDHHcR6LEOeMBpo="
  - secure: "grDEa1Q6hFWa72y9Ljh4oxzGECH3ELCByPpljWPdvesbNWQy2vZ1rMV0ri/LlLG10wNnofG78558TwSZTJ088gqdeUZn/a9A2QPsIFijXR6Tsr4oT6bXbbjxyp/akLOSDUcQnAAlUZBDn8DkKkgrCda7sDlOBj3/RWYHcXy7O2Fn0h3IZ8TAKEH4ImLBFIaXEnGJghGHKKtuLVUj234rZv1oXRzpQnE+rMOBUF+hhjoTymc6wurI3vs9rIGfOwLXXrJ45LQFN69b4iIm0+nuwISUsOJ3+bZL0QlZRpW4lwSKq2TXJWFdGYd5flwF9D+ZQ6Bz02q8pZsKNCcJBzBoJS4JslQiGRNhj7SQZd/6e9SiDzOupFFjTLgLLpXubXqw4AHPYJ+hJiasbYOV9XBI8rPT8NKY7w/zRbKExNW2LymckEj5v8BSGPaNMeTJ/ly7txX3qrra5ogmvY82kXJjo9w4YJ9bCj8ZONegAhN7b5BxSubbt9bCjKdvSEZKKmsEBKF/bCY9KgLoRDzJ4WYTNHQtnZNpbL4D6xmiytkmNQCgSMZxt6C8tWq5hjmk9v65M7v+7GdfXvC6c1rzH/raYmF6R7RrH82R1CMMKiLBHFGAYtE/OXbsYOHr0ROefGvmE8igzwafhDe4sIJbs/4ZO2KpbmsSaeV0RfDVefobipM="
  - AWS_DEFAULT_REGION: "us-east-1"
  - S3_PARAMS: '"--acl public-read --cache-control \"public,must-revalidate,proxy-revalidate,max-age=0\""'
  - CMAKE_BUILD_PARALLEL_LEVEL: 4
  - LINUX_CMAKE_PARAMS: '"-DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release"'

matrix:
  include:

  # -----------------
  - name: "Linux x64"
  # -----------------
    dist: xenial
    language: c
    compiler: gcc

    addons:
      apt:
        packages:
        - cmake
        - gcc-4.8
        - g++-4.8

    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin

    script:
    - mkdir build
    - cd build
    - "CC=gcc-4.8 CXX=g++-4.8 cmake $LINUX_CMAKE_PARAMS -DCMAKE_C_FLAGS=\"-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0\" -DCMAKE_SHARED_LINKER_FLAGS=-Wl,--wrap,memcpy .."
    - cmake --build .
    - strip code/libassimp.so
    - "git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git"
    - "aws s3 cp code/libassimp.so s3://build.lwjgl.org/nightly/linux/x64/ $S3_PARAMS"
    - "aws s3 cp revision.git s3://build.lwjgl.org/nightly/linux/x64/libassimp.so.git $S3_PARAMS"

  # -----------------
  - name: "Linux arm32"
  # -----------------
    dist: xenial
    language: c
    compiler: gcc

    addons:
      apt:
        packages:
        - cmake
        - gcc-4.8-arm-linux-gnueabihf
        - g++-4.8-arm-linux-gnueabihf
        - libc6-dev-armhf-cross

    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - sudo sed -i 's/deb http/deb [arch=amd64,i386] http/' /etc/apt/sources.list
    - sudo grep "ubuntu.com/ubuntu" /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/ports.list
    - sudo sed -i 's/amd64,i386/armhf,arm64/' /etc/apt/sources.list.d/ports.list
    - sudo sed -i 's#http://.*/ubuntu#http://ports.ubuntu.com/ubuntu-ports#' /etc/apt/sources.list.d/ports.list
    - sudo dpkg --add-architecture armhf
    - sudo apt-get update || true
    - sudo apt-get -yq install zlib1g-dev:armhf
    #- sudo apt-get -yq --no-install-suggests --no-install-recommends install zlib1g-dev:armhf

    script:
    - mkdir build
    - cd build
    - "CC=arm-linux-gnueabihf-gcc-4.8 CXX=arm-linux-gnueabihf-g++-4.8 cmake $LINUX_CMAKE_PARAMS -DCMAKE_C_FLAGS=\"-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0\" .."
    - cmake --build .
    - arm-linux-gnueabihf-strip code/libassimp.so
    - "git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git"
    - "aws s3 cp code/libassimp.so s3://build.lwjgl.org/nightly/linux/arm32/ $S3_PARAMS"
    - "aws s3 cp revision.git s3://build.lwjgl.org/nightly/linux/arm32/libassimp.so.git $S3_PARAMS"

  # -----------------
  - name: "Linux arm64"
  # -----------------
    dist: xenial
    language: c
    compiler: gcc

    addons:
      apt:
        packages:
        - cmake
        - gcc-4.8-aarch64-linux-gnu
        - g++-4.8-aarch64-linux-gnu
        - libc6-dev-arm64-cross

    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - sudo sed -i 's/deb http/deb [arch=amd64,i386] http/' /etc/apt/sources.list
    - sudo grep "ubuntu.com/ubuntu" /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/ports.list
    - sudo sed -i 's/amd64,i386/armhf,arm64/' /etc/apt/sources.list.d/ports.list
    - sudo sed -i 's#http://.*/ubuntu#http://ports.ubuntu.com/ubuntu-ports#' /etc/apt/sources.list.d/ports.list
    - sudo dpkg --add-architecture arm64
    - sudo apt-get update || true
    - sudo apt-get -yq install zlib1g-dev:arm64
    #- sudo apt-get -yq --no-install-suggests --no-install-recommends install zlib1g-dev:arm64

    script:
    - mkdir build
    - cd build
    - "CC=aarch64-linux-gnu-gcc-4.8 CXX=aarch64-linux-gnu-g++-4.8 cmake $LINUX_CMAKE_PARAMS -DCMAKE_C_FLAGS=\"-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0\" .."
    - cmake --build .
    - aarch64-linux-gnu-strip code/libassimp.so
    - "git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git"
    - "aws s3 cp code/libassimp.so s3://build.lwjgl.org/nightly/linux/arm64/ $S3_PARAMS"
    - "aws s3 cp revision.git s3://build.lwjgl.org/nightly/linux/arm64/libassimp.so.git $S3_PARAMS"

  # -----------------
  - name: "Linux mips64"
  # -----------------
    dist: xenial
    language: c
    compiler: gcc

    addons:
      apt:
        packages:
        - cmake
        - gcc-5-mips64el-linux-gnuabi64
        - g++-5-mips64el-linux-gnuabi64
        - libc6-dev-mips64el-cross

    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - sudo rm -rf /etc/apt/sources.list
    - sudo sh -c "echo 'deb http://deb.debian.org/debian stretch main' >> /etc/apt/sources.list"
    - sudo dpkg --add-architecture mips64el
    - sudo apt-get update || true
    - sudo apt-get -yq --allow-unauthenticated install zlib1g-dev:mips64el
    #- sudo apt-get -yq --no-install-suggests --no-install-recommends install zlib1g-dev:mips64

    script:
    - mkdir build
    - cd build
    - "CC=mips64el-linux-gnuabi64-gcc-5 CXX=mips64el-linux-gnuabi64-g++-5 cmake $LINUX_CMAKE_PARAMS -DCMAKE_C_FLAGS=\"-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0\" .."
    - cmake --build .
    - mips64el-linux-gnuabi64-strip code/libassimp.so
    - "git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git"
    - "aws s3 cp code/libassimp.so s3://build.lwjgl.org/nightly/linux/mips64/ $S3_PARAMS"
    - "aws s3 cp revision.git s3://build.lwjgl.org/nightly/linux/mips64/libassimp.so.git $S3_PARAMS"

  # -----------------
  - name: "macOS"
  # -----------------
    language: objective-c
    osx_image: xcode11.3
    compiler: clang

    before_install:
    - brew update

    install:
    - brew install awscli

    script:
    - mkdir build
    - cd build
    - "cmake $LINUX_CMAKE_PARAMS -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 .."
    - cmake --build .
    - strip -u -r code/libassimp.dylib
    - "git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git"
    - "aws s3 cp code/libassimp.dylib s3://build.lwjgl.org/nightly/macosx/x64/ $S3_PARAMS"
    - "aws s3 cp revision.git s3://build.lwjgl.org/nightly/macosx/x64/libassimp.dylib.git $S3_PARAMS"